export const ROLE_USER = 'USER';
export const ROLE_ADMIN = 'ADMIN';
export const ROLE_NUTRITIONIST = 'NUTRITIONIST';
export const ROLE_MODERATOR = 'MODERATOR';
export const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';

export const ROLES = {
  USER: ROLE_USER,
  ADMIN: ROLE_ADMIN,
  NUTRITIONIST: ROLE_NUTRITIONIST,
  MODERATOR: ROLE_MODERATOR,
  SUPER_ADMIN: ROLE_SUPER_ADMIN,
};
